--DEGÝÞKEN ATAMA
DECLARE @ISIM AS VARCHAR(50)='OMER'
SELECT @ISIM 


DECLARE @AD AS VARCHAR(50)
SET @AD='HASAN'
SELECT @AD

--DEGÝÞKENDE 4 ÝÞLEM 
DECLARE @SAYI AS INTEGER
SET @SAYI=15

DECLARE @SAYI2 AS INTEGER
SET @SAYI2=25

SELECT 
@SAYI2+@SAYI AS TOPLAMLARI,
@SAYI2-@SAYI AS FARKLARI



DECLARE @TARIH AS DATETIME
SET @TARIH = GETDATE()
SELECT @TARIH AS BUGUNTARIH

DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='KURSAT EMIN'

--KELIME BIRLESTIRME
SELECT SUBSTRING(@KELIME,8,4) AS IKINCIAD

--BUYUK KUCUK YAPMA
SELECT LOWER(@KELIME), UPPER(@KELIME)

--STRING BIRLESTIRME
DECLARE @AD AS VARCHAR(100)='KURSAT'
DECLARE @SOYAD AS VARCHAR(100)='BESIKTEPE'
SELECT @AD+' '+@SOYAD AS ISIMBIRLESTIRME

--RIGHT, LEFT(SOLDAN KAÇ KELÝME ALMAK ÝSTÝYORSAK)
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='KURSAT EMIN'
SELECT LEFT(@KELIME,6), RIGHT(@KELIME,4)

--BOSLUK TEMÝZLEME SOL LTRIM SAG RTRIM TRIM
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='   KURSAT    EMIN      '
SELECT LTRIM(@KELIME) AS LTRIMM,RTRIM(@KELIME) AS RTRIMM,TRIM(@KELIME) AS TRIMM

--KARAKTER DEGISTIRME TURKCE ING KARAKTERI DEGISTIRME REPLACE 
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='KURSAT EMIN'
SELECT REPLACE(@KELIME,'Ý','I')

--STRING IFADE UZUNLUGUNU GETIRIR LEN
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='KURSAT EMIN'
SELECT LEN(LEFT(@KELIME,3))

--STRING_SPLIT TABLO HALÝNDE GÖSTERÝR (MÝSAL VÝRGÜLE AYRILAN KISIMLARI TABLO YAPMIS)
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA,DUNYA'
SELECT * FROM 
string_split(@KELIME,',')


----------------------DATETÝME FONKSÝYONLARI-----------------------------
--DATEADD TARÝH EKLEME  (DAY MONTH HOUR YEAR MINUTE SECOND)
DECLARE @TARIH AS DATETIME
SET @TARIH='2019-01-01 16:21:37'

DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(DAY,6,@TARIH)  
SELECT @TARIH AS ESKI, @TARIH2 AS YENI


--DATEDIFF TARIH ARASI FARK YEAR MONTH DAY HOUR WEEK HAFTA 
DECLARE @TARIH AS DATETIME
SET @TARIH='2019-01-01 16:21:37'

DECLARE @TARIH2 AS DATETIME
SET @TARIH2='2020-01-01 16:21:37'

SELECT DATEDIFF(DAYOFYEAR,@TARIH,@TARIH2)

--DATEPART MILLISECOND MONTH DAY WEEK
DECLARE @TARIH AS DATETIME
SET @TARIH='2019-02-01 16:21:37'
--SELECT DATEPART(MONTH,@TARIH)
SELECT MONTH(@TARIH)

--GETDATE()
DECLARE @DOGUMTARIH AS DATETIME
SET @DOGUMTARIH='2000-09-01 16:21:37'
SELECT DATEDIFF(YEAR,@DOGUMTARIH,GETDATE()) AS YASINIZ


---------------------------------DONGULER-------------------------------------
DECLARE @SAYI AS INT=0
WHILE @SAYI<10
BEGIN
	SELECT @SAYI+@SAYI AS TOPLAM
	SET @SAYI = @SAYI +1
END

--TARÝH OTOMATÝK EKLEME

DECLARE @SAYI AS INT=0
WHILE @SAYI<6
BEGIN
	INSERT INTO DATES (BIRTHDAY) VALUES (GETDATE())
	WAITFOR DELAY'00:00:01'
	--SIFIR BIR MÝLÝSANÝYE BEKLEYEREK KAYIT EKLER
	SET @SAYI = @SAYI+1
END

SELECT * FROM NAME
SELECT * FROM SURNAME
SELECT * FROM USERS

DECLARE @SAYI AS INT=0
DECLARE @AD AS VARCHAR(50)
DECLARE @SOYAD AS VARCHAR(50)
DECLARE @CINSIYET AS VARCHAR(2)
DECLARE @DOGUMT AS DATE
DECLARE @YAS AS INT
DECLARE @YASGRUP AS VARCHAR(30)

WHILE @SAYI<1
BEGIN

SELECT @AD=NAMES,@CINSIYET=GENDER FROM NAME WHERE ID=ROUND(RAND()*200,0)
SELECT @SOYAD=SURNAMES FROM SURNAME WHERE ID=ROUND(RAND()*250,0)
SET @DOGUMT=DATEADD(DAY,ROUND(RAND()*17000,0),'1980-01-01')
SET @YAS = DATEDIFF(YEAR,@DOGUMT,GETDATE())
SELECT @AD,@SOYAD,@CINSIYET,@DOGUMT,@YAS

SET @SAYI = @SAYI+1

END
