USE BANK

------------------------------------------------
SELECT * FROM MONEYTRANSACTIONS
SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM ACCOUNTBALANCE B
INNER JOIN ACCOUNTS A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID
-----------------------------------------------------------


INSERT INTO MONEYTRANSACTIONS (ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
VALUES (1,2,1000,'2025-10-02 17:10:37','TL','12345678','')
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN
END

UPDATE ACCOUNTBALANCE SET BALANCE= BALANCE-1000 WHERE ACCOUNTID=1
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN
END


INSERT INTO MONEYTRANSACTIONS (ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
VALUES (2,1,1000,'2025-10-02 18:10:37','TL','12345678','0987654321')
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN
END


UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE+1000 WHERE ACCOUNTID=2
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN
END

---HATA YOKSA TAMAMLA----
COMMIT TRAN


--------------------------------------------------

BEGIN TRAN 
	INSERT INTO MONEYTRANSACTIONS (ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
	VALUES (1,2,1000,'2025-10-02 17:10:37','TL','12345678','')

	UPDATE ACCOUNTBALANCE SET BALANCE= BALANCE-1000 WHERE ACCOUNTID=1

	INSERT INTO MONEYTRANSACTIONS (ACCOUNTID, TRANTYPE, AMOUNT, DATE_, CURRENCY, EFTCODE1, EFTCODE2)
	VALUES (2,1,1000,'2025-10-02 18:10:37','TL','12345678','0987654321')

	UPDATE ACCOUNTBALANCE SET BALANCE=BALANCE+1000 WHERE ACCOUNTID=2
ROLLBACK TRAN


--------CLEAR TABLE---------------------------

TRUNCATE TABLE MONEYTRANSACTIONS
UPDATE ACCOUNTBALANCE SET BALANCE=1000 WHERE ACCOUNTID=1
UPDATE ACCOUNTBALANCE SET BALANCE=0 WHERE ACCOUNTID=2
