USE ETRADE 

SELECT * FROM ITEMS
---------TRANSACTION BITMESE BILE WITH NOLOCK KITLENMEYE TAKILMADAN DEVAM EDER---------------
SELECT * FROM ITEMS WITH (NOLOCK) WHERE ID=3

BEGIN TRAN
UPDATE ITEMS SET UNITPRICE=55 WHERE ID=3

SELECT * FROM  ITEMS_LOG WHERE ID=3
ROLLBACK