use ETRADE  
--databaseyi seçmek için kullanýlýr

create database ETRADE

create table CUSTOMERS(
		ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
		CUSTOMERNAME VARCHAR(100),
		CITY VARCHAR(50),
		BIRTHDATE DATE,
		DISTRICT VARCHAR(50),
		GENDER VARCHAR(1)
		);

INSERT INTO CUSTOMERS
VALUES ('ERDAL YILMAZ','RIZE','1971-08-16','CAYELI','E'),
('AYSE CETIN','RIZE','1969-08-16','SALAHA','K'),
('EMINE KABA','RIZE','1958-08-16','CAYELI','K')


ALTER TABLE CUSTOMERS ADD PHONE VARCHAR(10)

ALTER TABLE CUSTOMERS DROP COLUMN PHONE

ALTER TABLE CUSTOMERS ALTER COLUMN GENDER VARCHAR(1)

UPDATE CUSTOMERS
SET PHONE='5350288341'
WHERE GENDER='K';

UPDATE CUSTOMERS
SET PHONE='5350299356'
WHERE GENDER='E';

INSERT INTO CUSTOMERS (GENDER,PHONE)
VALUES ('E','5350223132')

SELECT * FROM CUSTOMERS

USE ETRADE

create table DATES (
				ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
				BIRTHDAY DATETIME,
);

DROP TABLE DATES

SELECT * FROM DATES


CREATE TABLE NAME(
				ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
				NAMES VARCHAR(40),
				GENDER VARCHAR(2)
)

CREATE TABLE SURNAME(
				ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
				SURNAMES VARCHAR(50)
)

CREATE TABLE USERS(
				ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
				NAMEE VARCHAR(40),
				SURNAMEE VARCHAR(50),
				GENDER VARCHAR(2),
				BIRTHDAYY DATE,
				AGE INT,
				AGECLASS VARCHAR(30)

)
