use ETRADE

CREATE VIEW ETALLVIEW
AS

SELECT U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS AD,C.COUNTRY AS ULKE,CT.CITY AS IL,T.TOWN AS ILCE,
O.ID,O.DATE_ AS GUN,ITM.ITEMCODE,ITM.ITEMNAME AS URUNAD,ITM.BRAND AS MARKA,
OD.AMOUNT AS ADET,OD.UNITPRICE AS FIYAT,OD.LINETOTAL AS SATIRTOP
FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID