--VIEW

SELECT IL,SUM(SATIRTOP) AS TOPLAMSATIR,COUNT(*) AS ADET 
FROM ETALLVIEW
GROUP BY IL	

SELECT * FROM ETALLVIEW

USE ETRADE

CREATE VIEW AYLARAGORE
AS
SELECT DATEPART(YEAR,GUN) YIL,
CASE
	WHEN DATEPART(MONTH,GUN)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,GUN)=2 THEN 'SBT'
	WHEN DATEPART(MONTH,GUN)=3 THEN 'MRT'
	WHEN DATEPART(MONTH,GUN)=4 THEN 'NSN'
	WHEN DATEPART(MONTH,GUN)=5 THEN 'MYS'
	WHEN DATEPART(MONTH,GUN)=6 THEN 'HZRAN'
	WHEN DATEPART(MONTH,GUN)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,GUN)=8 THEN 'AGUSTOS'
	WHEN DATEPART(MONTH,GUN)=9 THEN 'EYL'
	WHEN DATEPART(MONTH,GUN)=10 THEN 'EKM'
	WHEN DATEPART(MONTH,GUN)=11 THEN 'KASM'
	WHEN DATEPART(MONTH,GUN)=12 THEN 'ARLK'

END AS AY,
SUM(ADET) ADET, SUM(FIYAT) FIYAT, SUM(SATIRTOP) MUSTERISAYISI
FROM ETALLVIEW  
GROUP BY DATEPART(YEAR,GUN), DATEPART(MONTH,GUN)


SELECT * FROM AYLARAGORE
ORDER BY YIL,AY


SELECT TOP 100
U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,U.TELNR1,U.TELNR2,
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
C.COUNTRY AS ULKE,CT.CITY AS IL,T.TOWN AS ILCE,
A.ADDRESSTEXT ACIKADRES,O.ID SIPARISID,O.DATE_ SIPARISTARIHI,ITM.ITEMCODE URUNKODU,ITM.ITEMNAME AS URUNAD,ITM.BRAND AS MARKA,
OD.AMOUNT AS ADET,OD.UNITPRICE AS FIYAT,OD.LINETOTAL AS SATIRTOP
FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID