--VIEW

SELECT IL,SUM(SATIRTOP) AS TOPLAMSATIR,COUNT(*) AS ADET 
FROM ETALLVIEW
GROUP BY IL	

SELECT * FROM ETALLVIEW

USE ETRADE

CREATE VIEW AYLARAGORE
AS
SELECT DATEPART(YEAR,GUN) YIL,
CASE
	WHEN DATEPART(MONTH,GUN)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,GUN)=2 THEN 'SBT'
	WHEN DATEPART(MONTH,GUN)=3 THEN 'MRT'
	WHEN DATEPART(MONTH,GUN)=4 THEN 'NSN'
	WHEN DATEPART(MONTH,GUN)=5 THEN 'MYS'
	WHEN DATEPART(MONTH,GUN)=6 THEN 'HZRAN'
	WHEN DATEPART(MONTH,GUN)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,GUN)=8 THEN 'AGUSTOS'
	WHEN DATEPART(MONTH,GUN)=9 THEN 'EYL'
	WHEN DATEPART(MONTH,GUN)=10 THEN 'EKM'
	WHEN DATEPART(MONTH,GUN)=11 THEN 'KASM'
	WHEN DATEPART(MONTH,GUN)=12 THEN 'ARLK'

END AS AY,
SUM(ADET) ADET, SUM(FIYAT) FIYAT, SUM(SATIRTOP) MUSTERISAYISI
FROM ETALLVIEW  
GROUP BY DATEPART(YEAR,GUN), DATEPART(MONTH,GUN)


SELECT * FROM AYLARAGORE
ORDER BY YIL,AY