use ETRADE



SELECT TOP 100
U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,U.TELNR1,U.TELNR2,
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
C.COUNTRY AS ULKE,CT.CITY AS IL,T.TOWN AS ILCE,
A.ADDRESSTEXT ACIKADRES,O.ID SIPARISID,O.DATE_ SIPARISTARIHI,ITM.ITEMCODE URUNKODU,ITM.ITEMNAME AS URUNAD,ITM.BRAND AS MARKA,
OD.AMOUNT AS ADET,OD.UNITPRICE AS FIYAT,OD.LINETOTAL AS SATIRTOP
FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID

CREATE VIEW AYLARAGORE
AS
SELECT 
DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'SBT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MRT'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NSN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MYS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HZRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AGUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARLK'

END AS AY

,SUM(OD.AMOUNT) TOPLAMMIKTAR,SUM(LINETOTAL),
COUNT(OD.ID) URUNSAYISI,COUNT(DISTINCT O.ID) AS MUSTERISAYISI
FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID

GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)

