USE CRM2

CREATE FUNCTION DBO.CALCULATE_AGE(@BIRTHDATE AS DATE)
RETURNS INT
AS
BEGIN

	DECLARE @SONUC AS INT
	SET @SONUC = DATEDIFF(YEAR,@BIRTHDATE,GETDATE()) 
	RETURN @SONUC
END

SELECT TOP 100 * FROM CUSTOMERS WHERE ID=3

SELECT DBO.CALCULATE_AGE('19990101')

SELECT TOP 100 *,DBO.CALCULATE_AGE(BIRTHDATE) AS YAS 
FROM CUSTOMERS

