USE ETRADE

CREATE FUNCTION DBO.TOPLA(@SAYI1 AS INT,@SAYI2 AS INT)
RETURNS INT
AS
BEGIN

	DECLARE @SONUC AS INT
	SET @SONUC=@SAYI1+@SAYI2
	RETURN @SONUC

END
--SCALA VALUEDE GORUNUR CUNKU 1 ADET SONUC DONUYOR

SELECT DBO.TOPLA(15,20)



ALTER FUNCTION DBO.MONTHDATE_(@DATEES AS DATETIME)
RETURNS VARCHAR(10)
AS
BEGIN
		DECLARE @SONUC AS VARCHAR(10)

			IF DATEPART(MONTH,@DATEES)=1 SET @SONUC = '01.OCK'
			IF DATEPART(MONTH,@DATEES)=2 SET @SONUC = '02.SBT'
			IF DATEPART(MONTH,@DATEES)=3 SET @SONUC = '03.MRT'
			IF DATEPART(MONTH,@DATEES)=4 SET @SONUC = '04.NSN'
			IF DATEPART(MONTH,@DATEES)=5 SET @SONUC = '05.MYS'
			IF DATEPART(MONTH,@DATEES)=6 SET @SONUC = '06.HZRAN'
			IF DATEPART(MONTH,@DATEES)=7 SET @SONUC = '07.TEMMUZ'
			IF DATEPART(MONTH,@DATEES)=8 SET @SONUC = '08.AGUSTOS'
			IF DATEPART(MONTH,@DATEES)=9 SET @SONUC = '09.EYL'
			IF DATEPART(MONTH,@DATEES)=10 SET @SONUC = '10.EKM'
			IF DATEPART(MONTH,@DATEES)=11 SET @SONUC = '11.KASM'
			IF DATEPART(MONTH,@DATEES)=12 SET @SONUC = '12.ARLK'

		RETURN @SONUC
END

SELECT TOP 100 DBO.MONTHDATE_(GUN) FROM ETALLVIEW

