SELECT * FROM WORKERS WHERE WORKERBARCODE='9F0E4219-6B8B-4035-A6EB-B025C1B66362'
-----------------------------------------------------------------
ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN 

	IF EXISTS(SELECT * FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE)
		BEGIN
			SELECT 'KART DOGRU'
		END
	
	ELSE
		BEGIN
			SELECT 'KART GECERSÝZ'
		END
END

-----------------------------------------------------------------------------
EXEC SP_CARD_CONTROL @WORKERBARCODE = '9F0E4219-6B8B-4035-A6EB-B025C1B66362'


-----------------------------------------------------------------------

ALTER PROCEDURE SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN

		DECLARE @WORKERNAME AS VARCHAR(100)
		DECLARE @WORKERID AS INT

		SELECT @WORKERNAME = WORKERNAME, @WORKERID = ID 
		FROM WORKERS 
		WHERE WORKERBARCODE = @WORKERBARCODE

		IF @WORKERID IS NULL
			BEGIN
				RAISERROR('OKUTULAN KART KAYITLI DEGIL',16,1)
				RETURN
			END
		
		DECLARE @LASTIO AS VARCHAR(1)
		
		SELECT TOP 1 @LASTIO=IOTYPE FROM WORKERTRANSACTIONS 
		WHERE WORKERID=1 AND DATE_ >= CONVERT(DATE,GETDATE())
		ORDER BY DATE_ DESC

		IF @LASTIO=@IOTYPE
		BEGIN
			IF @IOTYPE = 'G'
			BEGIN
				RAISERROR('ZATEN ICERIDESINIZ, GIRIS YAPAMAZSINIZ',16,1)
				RETURN
			END
			IF @IOTYPE = 'C'
			BEGIN
				RAISERROR('ZATEN DISARIDASINIZ, CIKIS YAPAMAZSINIZ',16,1)
				RETURN
			END
		END

		INSERT INTO WORKERTRANSACTIONS (WORKERID, DATE_, IOTYPE, GATEID) 
		VALUES (@WORKERID,@DATE,@IOTYPE,@GATEID)

		SELECT @WORKERNAME AS WORKERNAME, @DATE AS DATE_,@IOTYPE AS IOTYPE
END

--------------------------------------------------------------------

TRUNCATE TABLE WORKERTRANSACTIONS

SELECT * FROM WORKERTRANSACTIONS ORDER BY DATE_ DESC

EXEC SP_WORKER_INOUT '9F0E4219-6B8B-4035-A6EB-B025C1B66362','2025-09-26 10:32:45','G',1

SELECT * FROM WORKERS



---------------------------------------------------------------------
USE ETRADE

---------------------------------------------------------------------
SELECT TOP 100
U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,U.TELNR1,U.TELNR2,
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
C.COUNTRY AS ULKE,CT.CITY AS IL,T.TOWN AS ILCE,
A.ADDRESSTEXT ACIKADRES,O.ID SIPARISID,O.DATE_ SIPARISTARIHI,ITM.ITEMCODE URUNKODU,ITM.ITEMNAME AS URUNAD,ITM.BRAND AS MARKA,
OD.AMOUNT AS ADET,OD.UNITPRICE AS FIYAT,OD.LINETOTAL AS SATIRTOP,
CONVERT(DATE,O.DATE_) AS SIPARISTARIHI, CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH,O.DATE_) AS AY

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID

WHERE O.DATE_ BETWEEN '20190101' AND '20190131'
-----------------------------------------------------------
ALTER PROC SP_SATISLAR
@BASTARIH DATE,
@BITTARIH DATE,
@SEHIR VARCHAR(50) = '%'
AS
BEGIN
		SELECT
		U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,U.TELNR1,U.TELNR2,
		ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
		C.COUNTRY AS ULKE,CT.CITY AS IL,T.TOWN AS ILCE,
		A.ADDRESSTEXT ACIKADRES,O.ID SIPARISID,O.DATE_ SIPARISTARIHI,ITM.ITEMCODE URUNKODU,ITM.ITEMNAME AS URUNAD,ITM.BRAND AS MARKA,
		OD.AMOUNT AS ADET,OD.UNITPRICE AS FIYAT,OD.LINETOTAL AS SATIRTOP,
		CONVERT(DATE,O.DATE_) AS SIPARISTARIHIYIL, CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
		DATEPART(YEAR,O.DATE_) AS YIL,
		DATEPART(MONTH,O.DATE_) AS AY

		FROM 
		ORDERDETAILS OD
		INNER JOIN ORDERS O ON OD.ORDERID=O.ID
		INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
		INNER JOIN USERS U ON U.ID=O.USERID
		INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
		INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
		INNER JOIN CITIES CT ON CT.ID=A.CITYID
		INNER JOIN TOWNS T ON T.ID = A.TOWNID
		INNER JOIN PAYMENTS P ON P.ORDERID=O.ID

		WHERE O.DATE_ BETWEEN @BASTARIH AND @BITTARIH
		AND CT.CITY LIKE @SEHIR

END

--------------------------------------

EXEC SP_SATISLAR '20190101','20190131'

INSERT INTO #RAPOR
EXEC SP_SATISLAR '20190101','20190131','ANKARA'

-----------------------------------
SET STATISTICS TIME ON

CREATE TABLE #RAPOR(
KULLANICIADI VARCHAR(100),
ADSOYAD VARCHAR(100),
TELNR1 VARCHAR(100),
TELNR2 VARCHAR(100),
CATEGORY1 VARCHAR(100),CATEGORY2 VARCHAR(100),CATEGORY3 VARCHAR(100),
CATEGORY4 VARCHAR(100),ULKE VARCHAR(100),IL VARCHAR(100),ILCE VARCHAR(100),ACIKADRES VARCHAR(500),
SIPARISID INT,SIPARISTARIHI VARCHAR(500),URUNKODU VARCHAR(500),URUNAD VARCHAR(500),
MARKA VARCHAR(500),ADET FLOAT,FIYAT FLOAT,
SATIRTOP FLOAT,SIPARISTARIHIYIL DATE,SIPARISZAMANI TIME,YIL INT,AY VARCHAR(50)
)
-------------------------------------
INSERT INTO #RAPOR
EXEC SP_SATISLAR '20190101','20200131'
-----------------------------------------
SELECT CATEGORY1,SUM(SATIRTOP) AS TOPLAM FROM #RAPOR GROUP BY CATEGORY1
SELECT * FROM #RAPOR
----------------------------------------------

SELECT *,DB_NAME(database_id) FROM sys.dm_exec_procedure_stats 
WHERE DB_NAME(database_id)='ETRADE'