CREATE DATABASE HR 

USE HR

CREATE TABLE WORKERS(
					ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
					WORKERCODE VARCHAR(20),
					WORKERNAME VARCHAR(50),
					GENDER VARCHAR(1),
					BIRTHDATE DATE,
					TCNO VARCHAR(11),
					WORKERBARCODE uniqueidentifier
    				)

CREATE TABLE WORKERTRANSACTIONS(
					ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
					WORKERID INT,
					DATE_ DATETIME,
					IOTYPE VARCHAR(1),
					GATEID INT,
    				)

INSERT INTO WORKERS (WORKERCODE, WORKERNAME, GENDER, BIRTHDATE, TCNO, WORKERBARCODE) 
VALUES ('12345678901', 'KURSAT EMIN BESIKTEPE','E','20000109','12345678901',NEWID())


INSERT INTO WORKERTRANSACTIONS (WORKERID, DATE_, IOTYPE, GATEID) 
VALUES (1,'2025-09-26 10:25:23','G',1)


SELECT * FROM WORKERS
SELECT * FROM WORKERTRANSACTIONS ORDER BY DATE_ DESC

