SELECT * FROM ITEMTRANSACTION
-----------------------------------------------------------------------------------
SELECT ID,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTION WHERE ITEMID=ITM.ID AND IOTYPE=1)-
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTION WHERE ITEMID=ITM.ID AND IOTYPE=2) AS STOCK
FROM ITEMS ITM
ORDER BY ID
--------------------------------------------------------------------------------------
CREATE TRIGGER TRG_TRANSACTION_INSERT
ON ITEMTRANSACTION
AFTER INSERT
AS
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @AMOUNT AS INT
	DECLARE @IOTYPE AS SMALLINT

	SELECT @ITEMID = ITEMID,@AMOUNT = AMOUNT,@IOTYPE=IOTYPE FROM INSERTED

	IF @IOTYPE=1
		UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID
	IF @IOTYPE=2
		UPDATE STOCK SET STOCK = STOCK - @AMOUNT WHERE ITEMID = @ITEMID
END

UPDATE STOCK SET STOCK = 0

TRUNCATE TABLE ITEMTRANSACTION

SELECT * FROM STOCK WHERE ITEMID = 4
SELECT * FROM ITEMTRANSACTION

INSERT INTO ITEMTRANSACTION (ITEMID,AMOUNT,IOTYPE, DATE_)
VALUES (4,25,1,GETDATE())

----------DELETETRIGGER--------------------------------------
CREATE TRIGGER TRG_TRANSACTION_DELETE
ON ITEMTRANSACTION
AFTER DELETE
AS
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @AMOUNT AS INT
	DECLARE @IOTYPE AS SMALLINT

	SELECT @ITEMID = ITEMID,@AMOUNT = AMOUNT,@IOTYPE=IOTYPE FROM DELETED

	IF @IOTYPE=1
		UPDATE STOCK SET STOCK = STOCK - @AMOUNT WHERE ITEMID = @ITEMID
	IF @IOTYPE=2
		UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID
END

---------------------------------------------------------------------

SELECT * FROM ITEMS WHERE ID=4
SELECT * FROM ITEMTRANSACTION WHERE ITEMID = 4
SELECT * FROM STOCK WHERE ITEMID=4

DELETE FROM ITEMTRANSACTION WHERE ID=2